### PR TITLE
Add Rubocop, Remove Backports

### PR DESCRIPTION
**Pull request by luke-hill**
## Summary

Added rubocop and removed backports gems

## Details

Added rubocop TODO's removed backports gem (No longer needed with up to date rubies)

## How Has This Been Tested?

rspec / CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I've added tests for my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by luke-hill** [comment]
2 points to note from this.

1) I didn't fix up cops as I figured this was best tackled in another PR
2) I also tried to tack on running on 2.7 in CI, but it blew things up. I'll add an issue to monitor.

**Comment by luke-hill** [comment]
NB: The failure here is related to the issue I created here: (Ruby 2.7+ doesn't play nice with protobuf)
https://github.com/cucumber/cucumber-ruby-core/issues/187 (So you can discount the failure on ruby-latest)

**Comment by luke-hill** [comment]
@vincent-psarga are you ok if I merge this in as well now?

**Comment by vincent-psarga** [comment]
yes no problem :)

**Pull request merged**
