### PR TITLE
Fix test suite for Ruby 2.4 compatibility.

### PR DESCRIPTION
**Pull request by junaruga**
## Summary

Fix test suite for Ruby 2.4 compatibility.

## Details

`bundle exec rake spec:warnings` is failed on Ruby 2.4
`bundle exec rake spec:slow` is succeed on Ruby 2.4

## Motivation and Context

Maybe we want to support cucumber on Ruby 2.4.

## How Has This Been Tested?

On latest master branch.
On Fedora 24

```
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux

$ bundle -v
Bundler version 1.13.7
```

```
$ bundle install --path vendor/bundle
```

Ignore the warnings under vendor as it is not checked on Travis CI.

```
$ bundle exec rake spec:warnings
...
/home/jaruga/git/cucumber-ruby-core/spec/coverage.rb:10:in `<top (required)>': [DEPRECATION] ::[] is deprecated. Use ::new instead.
...
/home/jaruga/git/cucumber-ruby-core/vendor/bundle/ruby/2.4.0/gems/simplecov-0.12.0/lib/simplecov/configuration.rb:207: warning: constant ::Fixnum is deprecated
/home/jaruga/git/cucumber-ruby-core/vendor/bundle/ruby/2.4.0/gems/simplecov-0.12.0/lib/simplecov/source_file.rb:29: warning: constant ::Fixnum is deprecated
/home/jaruga/git/cucumber-ruby-core/vendor/bundle/ruby/2.4.0/gems/simplecov-0.12.0/lib/simplecov/source_file.rb:30: warning: constant ::Fixnum is deprecated
...
rake aborted!
Please remove all cucumber-core warnings.
```

```
$ bundle exec rake spec:slow
...
1 example, 0 failures
```

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I've added tests for my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

Is it possible to add ruby 2.4.0 to `.travis.yml`?

### CODE REVIEW

**Comment by mattwynne** [comment]
@junaruga yes, please do add ruby 2.4 to the `.travis.yml` config as part of this PR.

**Comment by junaruga** [comment]
@mattwynne sorry, I saw your message now. Just moment. I will add it.

**Comment by junaruga** [comment]
Travis failed for onlly Ruby 2.4.0 test because of core dump.

https://travis-ci.org/cucumber/cucumber-ruby-core/jobs/197417468

```
$ bundle exec rake

/home/travis/.rvm/rubies/ruby-2.4.0/bin/ruby -r./spec/coverage -w -I/home/travis/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.5.4/lib:/home/travis/.rvm/gems/ruby-2.4.0/gems/rspec-support-3.5.0/lib /home/travis/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

Run options: exclude {:slow=>true}
...
348 examples, 0 failures
...
/home/travis/.rvm/gems/ruby-2.4.0/gems/simplecov-0.12.0/lib/simplecov/source_file.rb:84: [BUG] Segmentation fault at 0xfffffffffffffff9
...
Aborted (core dumped)

/home/travis/.rvm/rubies/ruby-2.4.0/bin/ruby -r./spec/coverage -w -I/home/travis/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.5.4/lib:/home/travis/.rvm/gems/ruby-2.4.0/gems/rspec-support-3.5.0/lib /home/travis/.rvm/gems/ruby-2.4.0/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed

2 non-cucumber-core warnings detected, set VIEW_OTHER_WARNINGS=true to see them.
```

**Comment by junaruga** [comment]
Now all the tests are passed after updating simplecv from 0.12.0 to latest version 0.13.0.
But this solution might be not good.
Because  cucumber-cury-core depends on coveralls (0.8.19).
coveralls (0.8.19) depends on simplecov (~> 0.12.0).

from local Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
...
    coveralls (0.8.19)
...
      simplecov (~> 0.12.0)
```

**Pull request merged**
