### PR TITLE
Changes for frozen string literals

### PR DESCRIPTION
**Pull request by twalpole**
Minor updates for compatibility with frozen string literals

### CODE REVIEW

**Comment by mattwynne** [comment]
I don't think the build failures are anything you've done. More likely something to do with #103.

**Comment by brasmusson** [comment]
Maybe it would have been better not to merge #103 as it did not updated the tests it broke

**Comment by mattwynne** [comment]
Agreed - my bad. I didn't notice it had broken anything when I merged it.

**Comment by aslakhellesoy** [comment]
How can we improve the CI notification so you're less likely to miss out on build errors @mattwynne?

**Comment by mattwynne** [comment]
I'm puzzled why I didn't see the Travis check in the PR. There was something weird about that PR. NM - it's not a big deal to fix.

**Comment by mattwynne** [comment]
Thanks @twalpole - immutability FTW! 👍

**Pull request merged**
